#!/usr/bin/env python3
"""Adapt MCP250 exact-model patch to the already-materialized MCP224 golden Agent runtime."""
from pathlib import Path

orig = Path(__file__).with_name("patch_mcp250_target_agent_families.py")
src = orig.read_text(encoding="utf-8")

old_steps = r'''steps_old = ''' + "'''        val currentSteps = compatToolStepsByModel[model.name] ?: 0\\n        if (currentSteps >= MAX_COMPAT_TOOL_STEPS) {\\n'''" + r'''
steps_new = ''' + "'''        val currentSteps = compatToolStepsByModel[model.name] ?: 0\\n        val mcp250ForceFinalization =\\n          Mcp250TargetAgentCompat.shouldForceFinalization(\\n            modelName = model.name,\\n            completedToolSteps = currentSteps,\\n            requestedToolName = parsedToolCall.toolName,\\n            previousToolName = mcp250LastCompatToolByModel[model.name],\\n          )\\n        if (mcp250ForceFinalization) {\\n          val guardTrips = mcp250LoopGuardTripsByModel[model.name] ?: 0\\n          viewModel.removeLastMessage(model = model)\\n          if (guardTrips >= 1) {\\n            viewModel.addMessage(\\n              model = model,\\n              message = ChatMessageInfo(content = \\\"MCP250 专项循环保护已停止再次工具调用；该模型未能在强制收敛后生成最终回复。\\\"),\\n            )\\n            compatToolStepsByModel.remove(model.name)\\n            mcp250LastCompatToolByModel.remove(model.name)\\n            mcp250LoopGuardTripsByModel.remove(model.name)\\n            updateProgressPanel(viewModel = viewModel, model = model, agentTools = agentTools)\\n            return@handleGenerationDone\\n          }\\n          mcp250LoopGuardTripsByModel[model.name] = guardTrips + 1\\n          viewModel.addMessage(\\n            model = model,\\n            message = ChatMessageInfo(content = \\\"MCP250 专项循环保护：沿用上一轮成功工具结果并进入最终回答阶段。\\\"),\\n          )\\n          continueCompatConversation?.invoke(\\n            model,\\n            Mcp250TargetAgentCompat.buildLoopGuardToolResult(\\n              originalUserRequest = originalUserRequest,\\n              requestedToolName = parsedToolCall.toolName,\\n            ),\\n          )\\n          return@handleGenerationDone\\n        }\\n        if (currentSteps >= MAX_COMPAT_TOOL_STEPS) {\\n'''" + r'''
screen = once(screen, steps_old, steps_new, "screen target loop guard")

increment_old = ''' + "'''        compatToolStepsByModel[model.name] = currentSteps + 1\\n        viewModel.removeLastMessage(model = model)\\n'''" + r'''
increment_new = ''' + "'''        compatToolStepsByModel[model.name] = currentSteps + 1\\n        if (Mcp250TargetAgentCompat.isTargetAgentModel(model.name)) {\\n          mcp250LastCompatToolByModel[model.name] = parsedToolCall.toolName\\n        }\\n        viewModel.removeLastMessage(model = model)\\n'''" + r'''
screen = once(screen, increment_old, increment_new, "screen remember target tool")
'''

new_steps = r'''steps_old = ''' + "'''        ModelLifecycleDiagnostics.record(\\n          context = context,\\n          modelName = model.name,\\n          stage = \\\"agent.compat.tool_call\\\",\\n          message = \\\"Compatibility tool call accepted without a fixed step limit\\\",\\n          detail = \\\"tool=${parsedToolCall.toolName}\\\",\\n        )\\n'''" + r'''
steps_new = ''' + "'''        val currentSteps =\\n          if (Mcp250TargetAgentCompat.isTargetAgentModel(model.name)) {\\n            compatToolStepsByModel[model.name] ?: 0\\n          } else {\\n            0\\n          }\\n        val mcp250ForceFinalization =\\n          Mcp250TargetAgentCompat.isTargetAgentModel(model.name) &&\\n            Mcp250TargetAgentCompat.shouldForceFinalization(\\n              modelName = model.name,\\n              completedToolSteps = currentSteps,\\n              requestedToolName = parsedToolCall.toolName,\\n              previousToolName = mcp250LastCompatToolByModel[model.name],\\n            )\\n        if (mcp250ForceFinalization) {\\n          val guardTrips = mcp250LoopGuardTripsByModel[model.name] ?: 0\\n          viewModel.removeLastMessage(model = model)\\n          if (guardTrips >= 1) {\\n            viewModel.addMessage(\\n              model = model,\\n              message = ChatMessageInfo(content = \\\"MCP250 专项循环保护已停止再次工具调用；该模型未能在强制收敛后生成最终回复。\\\"),\\n            )\\n            compatToolStepsByModel.remove(model.name)\\n            mcp250LastCompatToolByModel.remove(model.name)\\n            mcp250LoopGuardTripsByModel.remove(model.name)\\n            updateProgressPanel(viewModel = viewModel, model = model, agentTools = agentTools)\\n            return@handleGenerationDone\\n          }\\n          mcp250LoopGuardTripsByModel[model.name] = guardTrips + 1\\n          viewModel.addMessage(\\n            model = model,\\n            message = ChatMessageInfo(content = \\\"MCP250 专项循环保护：沿用上一轮成功工具结果并进入最终回答阶段。\\\"),\\n          )\\n          continueCompatConversation?.invoke(\\n            model,\\n            Mcp250TargetAgentCompat.buildLoopGuardToolResult(\\n              originalUserRequest = originalUserRequest,\\n              requestedToolName = parsedToolCall.toolName,\\n            ),\\n          )\\n          return@handleGenerationDone\\n        }\\n        if (Mcp250TargetAgentCompat.isTargetAgentModel(model.name)) {\\n          compatToolStepsByModel[model.name] = currentSteps + 1\\n          mcp250LastCompatToolByModel[model.name] = parsedToolCall.toolName\\n        }\\n        ModelLifecycleDiagnostics.record(\\n          context = context,\\n          modelName = model.name,\\n          stage = \\\"agent.compat.tool_call\\\",\\n          message = \\\"Compatibility tool call accepted without a fixed step limit\\\",\\n          detail = \\\"tool=${parsedToolCall.toolName}\\\",\\n        )\\n'''" + r'''
screen = once(screen, steps_old, steps_new, "screen target loop guard post-MCP224")
'''

if src.count(old_steps) != 1:
    raise SystemExit(f"MCP250 v2 screen transform count={src.count(old_steps)}")
src = src.replace(old_steps, new_steps, 1)

# Run the transformed original in its own namespace while preserving __file__ so repository roots stay correct.
code = compile(src, str(orig), "exec")
ns = {"__name__": "__main__", "__file__": str(orig)}
exec(code, ns, ns)
