name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature/**" ]
    paths:
      - 'Android/**'
      - '.github/workflows/build_android.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Android/**'

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Android/src
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build
        run: ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: local-agent-plaza-release
          path: Android/src/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
